### ISSUE TITLE
Incorrect error display when neither -w nor -k is present 

### ISSUE THREAD

**Issue by Hillosanation** [Marfung37/PC-Saves-Get#1]
https://github.com/Marfung37/PC-Saves-Get/blob/35db2759e1956df8c57e3b3122d679870c6f765c/sfinder-saves.py#L251
It triggers for this: `py sfinder-saves.py filter`
Perhaps it's the other way round, and neither were found?

**Comment by Marfung37** [comment]
There should've been a not in the if statement. Neither was found would be checked by the if statement after it
